name = "telegram-ai-assistant"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
# TELEGRAM_BOT_TOKEN = "your_telegram_bot_token_here"
# AI_PROVIDER_API_KEY = "your_ai_provider_api_key_here"

# Example for KV Namespace binding
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Example for D1 Database binding
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "counter"
database_id = "6cfad0f8-2f79-4516-881b-711f23d3cbf8"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



